--CREATE TABLE IF NOT EXISTS Movie (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    title VARCHAR(255) NOT NULL,
--    releaseYear INT NOT NULL,
--    votes INT NOT NULL,
--    rating DOUBLE NOT NULL,
--    image_url VARCHAR(255)
--);